[workspace]
resolver = "3"
members = [
    "crates/app",
    "crates/character",
    "crates/cli",
    "crates/gpui-tokio",
    "crates/persistence",
    "crates/shared"
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
app = { path = "crates/app" }
character = { path = "crates/character" }
gpui-tokio = { path = "crates/gpui-tokio" }
persistence = { path = "crates/persistence" }
shared = { path = "crates/shared" }
gpui-kit = { version = "0.6.0", default-features = false, features = ["component"] }
tokio = "1.53.0"
toasty = { version = "0.10.0", features = ["turso", "jiff", "serde", "migration"] }
toasty-driver-turso = "0.10.0"
toasty-cli = "0.10.0"
uuid = { version = "1.24.0", features = ["v7"] }
jiff = "0.2.34"
timeago = "0.6.1"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
rust-embed = "8.12.0"
directories = "6.0.0"
anyhow = "1.0.103"
