[workspace]
resolver = "3"
members = [
    "crates/app",
    "crates/settings",
    "crates/shared",
    "crates/view"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
settings = { path = "crates/settings" }
shared = { path = "crates/shared" }
view = { path = "crates/view" }
gpui-kit = "0.6.4"
rust-embed = "8.12.0"
directories = "6.0.0"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
anyhow = "1.0.104"
