[workspace]
resolver = "3"
members = ["crates/app", "crates/shared"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
shared = { path = "crates/shared" }
gpui-kit = { version = "0.6.4" }
rust-embed = "8.12.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
anyhow = "1.0.104"
