[package]
name = "app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "innscribe"
path = "src/main.rs"

[dependencies]
character.workspace = true
persistence.workspace = true
shared.workspace = true
gpui-kit.workspace = true
gpui-tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
