[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "innscribe"
path = "src/main.rs"

[dependencies]
shared.workspace = true
view.workspace = true
gpui-kit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
